---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  labels:
    app: rollouts-demo
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: "alexmt/rollouts-demo:latest"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
  strategy:
#     blueGreen:
#       #autoPromotionEnabled: false
#       activeService: rollouts-demo
#       previewService: rollouts-demo-preview
#       scaleDownDelaySeconds: 10
    canary:
      steps:
      - setWeight: 20
      - pause: {}
