apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
  labels:
    app: canary-demo
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
      - name: canary-demo
        image: alexmt/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
  strategy:
    canary:
      canaryService: canary-demo-preview
      steps:
      - setWeight: 25
      - pause: {}
